feat: CheckableSelectField - Custom MultiSelectField
hazelcast/hive pull request #356
Opened 2021-07-27 14:20 UTC by Sodik

2021-07-27 15:10 UTC, fantkolja requested changes
Well done!
Few comments...

2021-07-27 15:10 UTC, fantkolja commented on packages/ui/__stories__/CheckableSelectField.stories.tsx
> +export const OpenWithInputValueAndNoResults = Template.bind({})
When there is an input value, some options are filtered out and I click 'Select All' also the hidden options are selected. This doesn't feel right
![image](https://user-images.githubusercontent.com/13898415/127178969-55f35b3c-5575-4bab-ba30-028196294e1e.png)

2021-07-27 15:10 UTC, fantkolja commented on packages/ui/src/Select/CheckableSelectField.module.scss
> +@use './styles/constants' as c;
Seems like the checkbox is higher than the text
![image](https://user-images.githubusercontent.com/13898415/127179222-a3cec08a-a16b-4c59-853c-933d9476d098.png)

2021-07-27 19:28 UTC, utkukaratas approved these changes
overlaps a lot with MultiSelectField :/

2021-07-28 07:03 UTC, Sodik commented
I think we should review selects and perhaps remove react-select or refactor this component to make it more compatible with react-select way @pawelklasa

2021-07-30 08:37 UTC, fantkolja approved these changes

2021-07-30 08:37 UTC, fantkolja commented on packages/ui/__stories__/CheckableSelectField.stories.tsx
> +import React, { useState } from 'react'
nit: Probably we should wrap long options, wdut?
![image](https://user-images.githubusercontent.com/13898415/127626012-13df0169-ede0-466e-b464-3ad3752c0b32.png)

2021-07-30 12:39 UTC, merged