HZC-4932: Make label optional for some HIVE components
hazelcast/hive pull request #501
Opened 2023-07-11 14:56 UTC by yaya-usman

[HZC-4932](https://hazelcast.atlassian.net/browse/HZC-4932)

[HZC-4932]: https://hazelcast.atlassian.net/browse/HZC-4932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-07-11 14:56 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org:443/pull/badge/not_signed)](https://cla.hazelcast.org:443/hazelcast/hive?pullRequest=501) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.hazelcast.org:443/hazelcast/hive?pullRequest=501) before we can accept your contribution.<br/><hr/>**yaya-usman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org:443/check/hazelcast/hive?pullRequest=501) it.</sub>

2023-07-11 16:24 UTC, allfayn commented
Could we add components without labels to storybook stories?

2023-07-12 07:24 UTC, yaya-usman commented
@allfayn Yes we can, confirmed that already

2023-07-12 12:02 UTC, fantkolja requested changes

2023-07-12 12:02 UTC, fantkolja commented on packages/ui/src/Toggle.tsx
> +  label?: string | React.ReactNode
Check other components

2023-07-12 12:15 UTC, yaya-usman commented on packages/ui/src/Toggle.tsx
> +  label?: string | React.ReactNode
i think conditional rendering is not necessary in this case actually, i have tested this on storybook, it's not having any issue likewise all the components i made changes to. i have removed the label and included it to check the changes it works just fine.

2023-07-12 12:53 UTC, merged