HZC-5155: Hive card border update
hazelcast/hive pull request #507
Opened 2023-08-16 11:51 UTC by yaya-usman

[HZC-5155](https://hazelcast.atlassian.net/browse/HZC-5155)

2023-08-16 11:53 UTC, Sodik approved these changes

2023-08-16 12:21 UTC, fantkolja requested changes

2023-08-16 12:21 UTC, fantkolja commented on packages/ui/src/Card.module.scss
> +  border: c.$borderWidth solid c.$colorNeutral;
please regenerate screenshots

2023-08-16 12:21 UTC, fantkolja commented on packages/ui/src/Card.module.scss
> +  border: c.$borderWidth solid c.$colorNeutral;
to fix failing tests

2023-08-17 09:57 UTC, fantkolja approved these changes

2023-08-17 10:03 UTC, merged