Feature/upgrade react table to v8
hazelcast/hive pull request #584
Opened 2024-12-18 13:12 UTC by Sodik

2024-12-18 14:12 UTC, fantkolja approved these changes

2025-01-15 09:25 UTC, fantkolja requested changes

2025-01-15 09:25 UTC, fantkolja commented on packages/ui/src/Table/utils.tsx
> +  const width = isNaN(size) ? 0 : size
Modifying the program code to fix tests is never a good solution, but if it requires too much time to find the real problem with tests, I think this check won't harm anyone.

2025-01-15 10:17 UTC, Sodik commented on packages/ui/.loki/reference/chrome_minimal_Components_Table_Default.png
By design https://tanstack.com/table/latest/docs/framework/react/examples/column-sizing

2025-01-15 10:20 UTC, Sodik commented on packages/ui/src/Table/CellWrapper.tsx
> +            row[Number(cellIndex)] = typeof cell.getValue() !== 'object' ? String(cell.getValue()) : ''
Value is used only if it is not an object

2025-01-15 10:30 UTC, Sodik commented on packages/ui/.loki/reference/chrome_minimal_Components_Table_With_Columns_Ordering.png
There is a tooltip, but our default min-width of 60 is not sufficient for all possible controls. Therefore, it should be adjusted individually via column definitions on a table.

2025-01-15 10:31 UTC, Sodik commented on packages/ui/src/Table/Header.module.scss
> +  background: #e9f0f9;
Seems to be a unique color

2025-01-15 10:31 UTC, Sodik commented on packages/ui/.loki/reference/chrome_minimal_Components_Table_With_Expandable_Rows.png
Fixed. Thx

2025-01-15 11:37 UTC, Sodik commented on packages/ui/src/Table/utils.tsx
> +  const width = isNaN(size) ? 0 : size
fixed

2025-01-16 10:40 UTC, fantkolja approved these changes

2025-01-16 10:41 UTC, merged